-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE SCHEMA "ping";
--> statement-breakpoint
CREATE TABLE "ping"."users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ping"."ping.user_details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"email" text NOT NULL,
	"enrollment_number" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_details_enrollment_number_key" UNIQUE("enrollment_number")
);
--> statement-breakpoint
ALTER TABLE "ping"."users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "ping"."user_devices" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" bigint,
	"is_active" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"unique_device_id" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ping"."user_devices" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ping"."user_devices" ADD CONSTRAINT "user_devices_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "ping"."users"("id") ON DELETE no action ON UPDATE cascade;
*/